name: Update Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for doc

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
          pip install -r doc/requirements.txt  # Install Sphinx and any other dependencies

      - name: Build documentation
        run: |
          cd doc
          make html
          cd ..
  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: doc/_build/html/

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages
          git pull origin gh-pages

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: html

      - name: Deploy documentation
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "actions@github.com"
          cp -r html/* .
          git add .
          git commit -m "Update documentation"
          git push origin gh-pages