name: Update Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for docs_source

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
          pip install -r docs_source/requirements.txt  # Install Sphinx and any other dependencies

      - name: Build documentation
        run: |
          cd docs_source
          make html  # Replace 'html' with your desired output format (e.g., html, dirhtml, etc.)
          cd ..

      - name: Deploy documentation
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "actions@github.com"

          git checkout -B gh-pages
          rm -rf ./*
          cp -r docs_source/_build/html/* .

          git add .
          git commit -m "Update documentation"
          git push origin gh-pages

